parameters:
  docker-composition:
    traefik_v1:
      type: traefik_v1
      enabled: true
      conf:
        docker:
          exposedByDefault: "false"
      compose:
        version: '3.1'
        services:
          traefik_v1:
            hostname: traefik_v1
            image: traefik:v1.7.24
            command: -c /traefik.toml
            volumes:
              - /var/run/docker.sock:/var/run/docker.sock
              - ./traefik.toml:/traefik.toml
