parameters:
  docker-composition:
    traefik:
      type: traefik
      enabled: true
      conf:
        docker:
          exposedByDefault: "false"
      compose:
        version: '3.1'
        services:
          traefik:
            hostname: traefik
            image: traefik:v1.6.3
            command: -c /traefik.toml
            volumes:
              - /var/run/docker.sock:/var/run/docker.sock
              - ./traefik.toml:/traefik.toml
