parameters:
  docker-composition:
    traefik:
      enabled: true
      conf:
        docker:
          exposedbydefault: "false"
      compose:
        version: '3.1'
        services:
          traefik:
            hostname: saltmaster
            image: traefik:v1.5.0-rc5
            command: -c /traefik.toml
            volumes:
              - /var/run/docker.sock:/var/run/docker.sock
              - ./traefik.toml:/traefik.toml
