debug = {{ conf.get('debug', 'false') }}
logLevel = "{{ conf.get('logLevel', 'ERROR') }}"
providersThrottleDuration = "{{ conf.get('providersThrottleDuration', '2s') }}"

[entryPoints]
  [entryPoints.http]
  address = ":80"
{%- if 'acme' in conf %}
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
{%- endif %}

{%- if 'acme' in conf %}
{%- set acme = conf['acme'] %}
[acme]
email = "{{ acme['email'] }}"
storage = "{{ acme.get('storage', 'acme.json') }}"
entryPoint = "https"
acmeLogging =  {{ acme.get('acmeLogging', 'false') }}
onHostRule = {{ acme.get('onHostRule', 'false') }}
{%- for d in acme.get('domains', []) %}
[[acme.domains]]
  main = "{{ d['main'] }}"
  {%- if 'sans' in d %}
  sans = [{% for x in d['sans'] %}"{{x}}"{% if not loop.last %},{% endif %}{% endfor %}]
  {%- endif %}
{%- endfor %}
[acme.httpChallenge]
  entryPoint = "http"
{%- endif %}

[api]
{%- set api = conf.get('api', {}) %}
entryPoint = "{{ api.get('entryPoint', 'traefik') }}"
dashboard = {{ api.get('dashboard', 'true') }}
debug = {{ api.get('debug', 'false') }}

[docker]
{%- set docker = conf.get('docker', {}) %}
endpoint = "{{ docker.get('endpoint', 'unix:///var/run/docker.sock') }}"
domain = "{{ docker.get('domain', 'docker.localhost') }}"
watch = {{ docker.get('watch', 'true') }}
exposedByDefault = {{ docker.get('exposedByDefault', 'false') }}
swarmMode = {{ docker.get('swarmMode', 'false') }}
